"use strict";

const use = require( "../lib/use" );
const { loadOptions } = require( "@babel/core" );

/**
 * Returns an object containing what to expect from this preset:
 *
 * * `options` The object passed to this function
 * * `preset` The generated options when this preset is used
 * * `babel` The options generated by babel with only this preset
 *
 * @param {{}} [options]
 */

function preview( options ) {

    const preset = use( null, options );
    const babel = loadOptions( preset );

    return { options, preset, babel };

}

module.exports = { preview, use };
