import { use } from "./preset";
import { loadOptions } from "babel-core";

/**
 * Returns an object containing what to expect from this preset:
 *
 * * `options` The object passed to this function
 * * `preset` The generated options when this preset is used
 * * `babel` The options generated by babel with only this preset
 *
 * @param {object} [options]
 */

export default function preview( options ) {

    const preset = use( null, options );
    const babel = loadOptions( preset );

    return { options, preset, babel };

}
